language: php
php:
  - '5.6'

install:
  - composer self-update
  - make install

script: make lint test

after_success:
  - travis_retry composer exec 'coveralls -v'

notifications:
  slack: radioteria:ZqNvcH9U10QXgCWfTXewf3Mf